Models/Champion.cs
namespace tftChampTraitViewer.Models;

public class Champion
{
    public int Id { get; set; }
    public string ChampName { get; set; }
    public string ChampGender { get; set; }
    public string ChampOrigin { get; set; }
    public string ChampClass { get; set; }
    public string ChampCost { get; set; }
    public string ChampRange { get; set; }
    public string ChampPosition { get; set; }

    public Champion()
    {
        
    }
}

Models/ErrorViewModel.cs
namespace tftChampTraitViewer.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Controllers/ChampionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using tftChampTraitViewer.Data;
using tftChampTraitViewer.Models;

namespace tftChampTraitViewer.Controllers
{
    public class ChampionController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ChampionController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Champion
        public async Task<IActionResult> Index()
        {
            return View(await _context.Champion.ToListAsync());
        }

        // GET: Champion/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var champion = await _context.Champion
                .FirstOrDefaultAsync(m => m.Id == id);
            if (champion == null)
            {
                return NotFound();
            }

            return View(champion);
        }

        // GET: Champion/Create
        public IActionResult Create()
        {
            return View();
        }
        // GET: Champion/ShowSearchForm
        public async Task<IActionResult> ShowSearchForm()
        {
            return View();
        }

        // POST: Champion/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ChampName,ChampGender,ChampOrigin,ChampClass,ChampCost,ChampRange,ChampPosition")] Champion champion)
        {
            if (ModelState.IsValid)
            {
                _context.Add(champion);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(champion);
        }

        // GET: Champion/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var champion = await _context.Champion.FindAsync(id);
            if (champion == null)
            {
                return NotFound();
            }
            return View(champion);
        }

        // POST: Champion/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ChampName,ChampGender,ChampOrigin,ChampClass,ChampCost,ChampRange,ChampPosition")] Champion champion)
        {
            if (id != champion.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(champion);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ChampionExists(champion.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(champion);
        }

        // GET: Champion/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var champion = await _context.Champion
                .FirstOrDefaultAsync(m => m.Id == id);
            if (champion == null)
            {
                return NotFound();
            }

            return View(champion);
        }

        // POST: Champion/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var champion = await _context.Champion.FindAsync(id);
            if (champion != null)
            {
                _context.Champion.Remove(champion);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ChampionExists(int id)
        {
            return _context.Champion.Any(e => e.Id == id);
        }
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using tftChampTraitViewer.Models;

namespace tftChampTraitViewer.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Views/Champion/Create.cshtml
@model tftChampTraitViewer.Models.Champion

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Champion</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ChampName" class="control-label"></label>
                <input asp-for="ChampName" class="form-control" />
                <span asp-validation-for="ChampName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ChampGender" class="control-label"></label>
                <input asp-for="ChampGender" class="form-control" />
                <span asp-validation-for="ChampGender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ChampOrigin" class="control-label"></label>
                <input asp-for="ChampOrigin" class="form-control" />
                <span asp-validation-for="ChampOrigin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ChampClass" class="control-label"></label>
                <input asp-for="ChampClass" class="form-control" />
                <span asp-validation-for="ChampClass" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ChampCost" class="control-label"></label>
                <input asp-for="ChampCost" class="form-control" />
                <span asp-validation-for="ChampCost" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ChampRange" class="control-label"></label>
                <input asp-for="ChampRange" class="form-control" />
                <span asp-validation-for="ChampRange" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ChampPosition" class="control-label"></label>
                <input asp-for="ChampPosition" class="form-control" />
                <span asp-validation-for="ChampPosition" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Champion/Delete.cshtml
@model tftChampTraitViewer.Models.Champion

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Champion</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ChampName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ChampName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ChampGender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ChampGender)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ChampOrigin)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ChampOrigin)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ChampClass)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ChampClass)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ChampCost)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ChampCost)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ChampRange)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ChampRange)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ChampPosition)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ChampPosition)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Champion/Details.cshtml
@model tftChampTraitViewer.Models.Champion

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Champion</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ChampName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ChampName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ChampGender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ChampGender)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ChampOrigin)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ChampOrigin)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ChampClass)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ChampClass)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ChampCost)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ChampCost)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ChampRange)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ChampRange)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ChampPosition)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ChampPosition)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Champion/Edit.cshtml
@model tftChampTraitViewer.Models.Champion

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Champion</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="ChampName" class="control-label"></label>
                <input asp-for="ChampName" class="form-control" />
                <span asp-validation-for="ChampName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ChampGender" class="control-label"></label>
                <input asp-for="ChampGender" class="form-control" />
                <span asp-validation-for="ChampGender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ChampOrigin" class="control-label"></label>
                <input asp-for="ChampOrigin" class="form-control" />
                <span asp-validation-for="ChampOrigin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ChampClass" class="control-label"></label>
                <input asp-for="ChampClass" class="form-control" />
                <span asp-validation-for="ChampClass" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ChampCost" class="control-label"></label>
                <input asp-for="ChampCost" class="form-control" />
                <span asp-validation-for="ChampCost" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ChampRange" class="control-label"></label>
                <input asp-for="ChampRange" class="form-control" />
                <span asp-validation-for="ChampRange" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ChampPosition" class="control-label"></label>
                <input asp-for="ChampPosition" class="form-control" />
                <span asp-validation-for="ChampPosition" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Champion/Index.cshtml
@model IEnumerable<tftChampTraitViewer.Models.Champion>

@{
    ViewData["Title"] = "Champion Table";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Champion Table</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ChampName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ChampGender)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ChampOrigin)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ChampClass)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ChampCost)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ChampRange)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ChampPosition)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ChampName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ChampGender)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ChampOrigin)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ChampClass)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ChampCost)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ChampRange)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ChampPosition)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - tftChampTraitViewer</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/tftChampTraitViewer.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">tftChampTraitViewer</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Champion" asp-action="Index">Champion List</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Champion" asp-action="ShowSearchForm">Search</a>
                    </li>
                </ul>
                <partial name="_LoginPartial"/>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2024 - tftChampTraitViewer - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>